### ISSUE TITLE
Probit Scale in Matplotlib 1.3.1

### ISSUE THREAD

**Issue by adbirch** [gnilson/ProbitScale#1]
Hi, 
I've used the probit scale class successfully with Matplotlib 1.1.1, but have found that it no longer works with version 1.3.1.

![figure_1](https://f.cloud.github.com/assets/6553957/2051000/113829c4-8a81-11e3-94a8-a98c322d7f9f.png)

My attempts to debug it have so far failed - do you intend to support newer versions of Matplotlib?

Regards

**Comment by gnilson** [comment]
Hey I'll look into this

**Comment by gnilson** [comment]
Try example.py in the latest commit. I just had to make sure the lognormal best-fit data was sorted to fix the plotting of the best fit line. I suppose this was due to a change in sicpy.stats.lognorm.

**Comment by adbirch** [comment]
Hi, thanks for looking into this - however, the Probit scale still doesn't seem to be honoured in the newer version of Matplot lib. The first image below runs your latest example.py against Matplotlib 1.1.1, the second against 1.3.1:

![111](https://f.cloud.github.com/assets/6553957/2124690/b11561cc-9243-11e3-9ad2-d886ccd85317.png)

![131](https://f.cloud.github.com/assets/6553957/2124693/b95b3924-9243-11e3-97e2-af3adf5db9d1.png)

**Comment by gnilson** [comment]
For some reason Matplotlib 1.3.1 needs a method called 'transform_non_affine' for all matplotlib.transforms.Transform classes. Previous versions worked fine using a simply named 'transform' method. See if the latest commit works for you. Also, thank you for your feedback on this.

![figure_2](https://f.cloud.github.com/assets/640523/2134328/c8615bea-92e0-11e3-8840-5e22db3fb271.png)

**Comment by adbirch** [comment]
Great, that works for me now in 1.3.1. Thanks for fixing and sharing this.
